name: 恢复singbox和socks5和nezha服务并发送Telegram消息

on:
  schedule:
    - cron: '0 20 * * *'  # 北京时间每1天4:00执行一次（时差8小时）
  workflow_dispatch:

jobs:
  restore_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装sshpass
        run: sudo apt-get install -y sshpass

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 执行Python脚本恢复singbox和hy2和nezha并发送Telegram消息
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 recover_singbox.py
